### ISSUE TITLE
Add analysis_result_string table loading

### ISSUE THREAD

**Issue by jfy133** [sidora-tools/sidora.core#30]
I was preparing a pandora-explorer thing the last couple of nights and realised we still have not yet implementd the loading of the analysis tables. If we want more people to use sidora.core etc. for stuff like that, we should do this as a basic functionality.

The main issue is the IDs and the results are decoupled across two tables (as in the results table doesn't actually display the Full_Analysis_ID). 

My question would be whether we should make a custom loading procedure for analysis (similar to the restricted access), or keep them decoupled and ask a user to major them. It only takes a few minutes to load the actual analysis results data (even if it's quite bag) so isn't unreasonable to allow loading atm.

Thoughts?

**Comment by nevrome** [comment]
Laura asked me about the same - this issue is absolutely valid.

If I understand this correctly, then there is a redundant intermediate table between `TAB_Raw_Data` and `TAB_Analysis`? You suggest we merge these automatically, ja?

I say we stay as close as possible to Pandora and keep them separate. And then we add a sentence to our Quickstart guide README and make the user aware of this technical detail. That's more easy for us and also more future proof in case this intermediate table gets additional columns one day.

**Comment by jfy133** [comment]
I didn't fully understand your comment, but agree with the concept of keeping close to Pandora as possible.

To clarify: Raw data != Analysis. The former is raw fastqs out of demultiplexing, the latter is various automated mapping pipelines from Kay.

If you do want to follow the Pandora page as close as possible (based on the tabs):

Then we will have

Sidora entity |  Pandora TAB
--------------------|-----------------------
raw_data       |  TAB_Raw_Data
analysis.        |  TAB_Analysis + TAB_Analysis_Result_String*

* These need to be merged on call with `get_df` with special function akin to acess_restricted_tables.

I actually have this solution half done (on a branch, can't remember if I pushed it though), but changed strategy halfway through so didn't finish it.

However if you have free time and Laura needs it soon, feel free to come up with your own (likely much more efficient solution!), It's a very simple left_join basically.

**Comment by jfy133** [comment]
Added in #31
